import type { ProjectAnswers, QuestionItem } from './types'

export const QUESTION_ITEMS: QuestionItem[] = [
  {
    key: 'idea',
    stage: 'المرحلة الأولى: الهوية',
    title: 'إيه هي فكرة مشروعك؟',
    helpText: 'اشرح حلمك ببساطة.',
    inputType: 'textarea',
    placeholder: 'اكتب وصف مختصر لفكرة المشروع...',
    maxLength: 350,
  },
  {
    key: 'sector',
    stage: 'المرحلة الأولى: الهوية',
    title: 'تصنيف نشاط المشروع الرئيسي؟',
    inputType: 'options',
    options: ['مطعم', 'تجارة', 'خدمات', 'تعليم', 'تقنية', 'صناعة'],
  },
  {
    key: 'legalStatus',
    stage: 'المرحلة الأولى: الهوية',
    title: 'الوضع القانوني الحالي؟',
    inputType: 'options',
    options: ['مجرد فكرة', 'بدأت في التراخيص', 'مشروع شغال فعلا'],
  },
  {
    key: 'audience',
    stage: 'المرحلة الثانية: السوق والعملاء',
    title: 'من هو العميل المستهدف؟',
    inputType: 'options',
    options: ['أفراد', 'شركات', 'ناس بتدور على التوفير', 'ناس بتدور على الرفاهية'],
  },
  {
    key: 'geoScope',
    stage: 'المرحلة الثانية: السوق والعملاء',
    title: 'النطاق الجغرافي للنشاط؟',
    inputType: 'options',
    options: ['حي أو منطقة', 'محافظة', 'مصر كلها', 'خارج مصر'],
  },
  {
    key: 'customerReason',
    stage: 'المرحلة الثانية: السوق والعملاء',
    title: 'ليه العميل هيختارك أنت بالذات؟',
    inputType: 'options',
    options: ['سعري أرخص', 'جودتي أعلى', 'خدمتي أسهل', 'معاملتي أحسن'],
  },
  {
    key: 'marketState',
    stage: 'المرحلة الثانية: السوق والعملاء',
    title: 'حالة السوق اللي هتدخله؟',
    inputType: 'options',
    options: ['فكرة جديدة محدش عملها', 'سوق عليه طلب عالي', 'المنافسة فيه صعبة'],
  },
  {
    key: 'competitors',
    stage: 'المرحلة الثانية: السوق والعملاء',
    title: 'مين منافسينك الأساسيين؟',
    inputType: 'options',
    options: ['شركات كبيرة', 'محلات مشابهة في المنطقة', 'مواقع أونلاين'],
  },
  {
    key: 'deliveryChannel',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'هتقدم منتجك للناس إزاي؟',
    inputType: 'options',
    options: ['محل أو مكتب', 'أونلاين', 'توصيل فقط', 'ميكس بين أكثر من قناة'],
  },
  {
    key: 'revenueModel',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'هتكسب فلوسك إزاي؟',
    inputType: 'options',
    options: ['بيع مباشر', 'اشتراكات', 'عمولة وسيط'],
  },
  {
    key: 'acquisitionChannel',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'هتوصل للناس إزاي؟',
    inputType: 'options',
    options: ['سوشيال ميديا', 'مندوبين مبيعات', 'إعلانات في الشارع', 'أكثر من طريقة'],
  },
  {
    key: 'teamSize',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'ناوي تبدأ بمشروع حجمه قد إيه؟',
    helpText: 'اختر أقرب حجم للفريق عند البداية.',
    inputType: 'options',
    options: [
      'لوحدي',
      'فريق صغير جدا (2-5)',
      'شركة صغيرة (6-20)',
      'كيان كبير (أكثر من 20)',
    ],
  },
  {
    key: 'techNeed',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'الاحتياج التكنولوجي؟',
    inputType: 'options',
    options: [
      'بسيط (إكسيل + واتساب)',
      'متوسط (موقع أو نظام تشغيل)',
      'متقدم (تطبيق + ذكاء اصطناعي)',
    ],
  },
  {
    key: 'experience',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'مستوى خبرة فريقك؟',
    inputType: 'options',
    options: ['مبتدئين', 'عندنا خبرة عملية', 'خبراء متخصصين'],
  },
  {
    key: 'location',
    stage: 'المرحلة الثالثة: التشغيل والتنفيذ',
    title: 'سهولة تلاقي موظفين شاطرين؟',
    inputType: 'options',
    options: ['متوفرين', 'متوفرين لكن غاليين', 'نادرين وصعب نلاقيهم'],
  },
  {
    key: 'budget',
    stage: 'المرحلة الرابعة: التوقعات المالية',
    title: 'رأس المال اللي هتبدأ بيه؟',
    inputType: 'options',
    options: ['أقل من 100 ألف', 'حتى 500 ألف', 'حتى 2 مليون', 'أكثر من 2 مليون'],
  },
  {
    key: 'fundingSource',
    stage: 'المرحلة الرابعة: التوقعات المالية',
    title: 'هتجيب الفلوس منين؟',
    inputType: 'options',
    options: ['تحويشة شخصية', 'شركاء', 'قرض', 'مستثمرين'],
  },
  {
    key: 'topExpense',
    stage: 'المرحلة الرابعة: التوقعات المالية',
    title: 'أكتر حاجة هتصرف فيها فلوس؟',
    inputType: 'options',
    options: ['إيجار', 'مرتبات', 'خامات', 'تسويق'],
  },
  {
    key: 'pricingModel',
    stage: 'المرحلة الرابعة: التوقعات المالية',
    title: 'هتسعر منتجك بناء على إيه؟',
    inputType: 'options',
    options: ['التكلفة + هامش ربح', 'قريب من المنافسين', 'سعر أقل للدخول للسوق'],
  },
  {
    key: 'monthlySalesTarget',
    stage: 'المرحلة الرابعة: التوقعات المالية',
    title: 'توقعك للأرباح الشهرية؟',
    inputType: 'options',
    options: ['أقل من 20 ألف', 'حتى 50 ألف', 'حتى 100 ألف', 'أكثر من 100 ألف'],
  },
  {
    key: 'demandOutlook',
    stage: 'المرحلة الخامسة: التوقعات والمخاطر',
    title: 'شايف الطلب على فكرتك هيكون إزاي؟',
    inputType: 'options',
    options: ['ضعيف', 'متوسط', 'عالي جدا'],
  },
  {
    key: 'seasonality',
    stage: 'المرحلة الخامسة: التوقعات والمخاطر',
    title: 'هل مشروعك مرتبط بمواسم معينة؟',
    inputType: 'options',
    options: ['شغال طول السنة', 'يرتبط بالمواسم والأعياد'],
  },
  {
    key: 'risks',
    stage: 'المرحلة الخامسة: التوقعات والمخاطر',
    title: 'أكبر خطر ممكن يواجهك؟',
    inputType: 'options',
    options: ['تغير الأسعار', 'منافس قوي', 'مشاكل قانونية', 'نقص خامات'],
  },
  {
    key: 'twoYearGoal',
    stage: 'المرحلة الخامسة: التوقعات والمخاطر',
    title: 'طموحك إيه بعد سنتين؟',
    inputType: 'options',
    options: ['فتح فروع جديدة', 'التوسع بنظام فرنشايز', 'السيطرة على السوق'],
  },
]

/** Ordered strings for `POST /project/step2` (one entry per `QUESTION_ITEMS` row). */
export function projectAnswersToStep2List(answers: ProjectAnswers): string[] {
  return QUESTION_ITEMS.map((item) => (answers[item.key] ?? '').trim())
}

export type { ProjectAnswers, ProjectAnswerKey } from './types'
